[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "docker build --build-arg BUILDKIT_INLINE_CACHE=1 ."

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
HOST = "0.0.0.0"
RELOAD = "false"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
PIP_NO_CACHE_DIR = "1"
