[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8000"
HOST = "0.0.0.0"
RELOAD = "false"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"
